# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='com.autodesk.thunderstorm.api',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x12\x1d\x63om.autodesk.thunderstorm.api\"p\n\x05Value\x12\x31\n\x04\x61tom\x18\x01 \x01(\x0b\x32#.com.autodesk.thunderstorm.api.Atom\x12\x34\n\x06values\x18\x02 \x03(\x0b\x32$.com.autodesk.thunderstorm.api.Value\"K\n\x04\x41tom\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x11\n\tunique_id\x18\x03 \x01(\x04\x12\x0f\n\x07preview\x18\x04 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='com.autodesk.thunderstorm.api.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='atom', full_name='com.autodesk.thunderstorm.api.Value.atom', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='com.autodesk.thunderstorm.api.Value.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=156,
)


_ATOM = _descriptor.Descriptor(
  name='Atom',
  full_name='com.autodesk.thunderstorm.api.Atom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type_name', full_name='com.autodesk.thunderstorm.api.Atom.type_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.autodesk.thunderstorm.api.Atom.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='com.autodesk.thunderstorm.api.Atom.unique_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preview', full_name='com.autodesk.thunderstorm.api.Atom.preview', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=233,
)

_VALUE.fields_by_name['atom'].message_type = _ATOM
_VALUE.fields_by_name['values'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['Atom'] = _ATOM

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:com.autodesk.thunderstorm.api.Value)
  ))
_sym_db.RegisterMessage(Value)

Atom = _reflection.GeneratedProtocolMessageType('Atom', (_message.Message,), dict(
  DESCRIPTOR = _ATOM,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:com.autodesk.thunderstorm.api.Atom)
  ))
_sym_db.RegisterMessage(Atom)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
